- name: Unmount volume from directory
 mount: 
    path: /mnt
    state: unmounted
- name: Format disk
 filesystem: 
    fstype: ext4
    dev: /dev/vdb
- name: Creates directory for volume
  file: 
    path: /home/ubuntu/docker
    state: directory
    mode: 0777
- name: Mount volume to directory
  mount: 
    path: /home/ubuntu/docker
    src: /dev/vdb
    fstype: ext4
    state: mounted
- name: Install software
  apt: name={{item}}
  with_items: 
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  force: yes
  update_cache: yes
  state: latest
- name: Add docker GPG key
  apt-key: url=https://download.docker.com/linux/ubuntu/gpg
- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
- name: Install Docker
  apt: name=docker-ce
  update_cache: yes
  state: latest